let codeArray = {
  0: ["Soleil", 2],
  1: ["Peu nuageux", 6],
  2: ["Ciel voilé", 6],
  3: ["Nuageux", 6],
  4: ["Très nuageux", 10],
  5: ["Couvert", 10],
  6: ["Brouillard", 0],
  7: ["Brouillard givrant", 0],
  10: ["Pluie faible", 8],
  11: ["Pluie modérée", 8],
  12: ["Pluie forte", 9],
  13: ["Pluie faible verglaçante", 8],
  14: ["Pluie modérée verglaçante", 8],
  15: ["Pluie forte verglaçante", 9],
  16: ["Bruine", 8],
  20: ["Neige faible", 5],
  21: ["Neige modérée", 5],
  22: ["Neige forte", 5],
  30: ["Pluie et neige mêlées faibles", 5],
  31: ["Pluie et neige mêlées modérées", 5],
  32: ["Pluie et neige mêlées fortes", 5],
  40: ["Averses de pluie locales et faibles", 8],
  41: ["Averses de pluie locales", 9],
  42: ["Averses locales et fortes", 9],
  43: ["Averses de pluie faibles", 8],
  44: ["Averses de pluie", 9],
  45: ["Averses de pluie fortes", 9],
  46: ["Averses de pluie faibles et fréquentes", 8],
  47: ["Averses de pluie fréquentes", 9],
  48: ["Averses de pluie fortes et fréquentes", 9],
  60: ["Averses de neige localisées et faibles", 8],
  61: ["Averses de neige localisées", 5],
  62: ["Averses de neige localisées et fortes", 5],
  63: ["Averses de neige faibles", 5],
  64: ["Averses de neige", 5],
  65: ["Averses de neige fortes", 5],
  66: ["Averses de neige faibles et fréquentes", 5],
  67: ["Averses de neige fréquentes", 5],
  68: ["Averses de neige fortes et fréquentes", 5],
  70: ["Averses de pluie et neige mêlées localisées et faibles", 5],
  71: ["Averses de pluie et neige mêlées localisées", 5],
  72: ["Averses de pluie et neige mêlées localisées et fortes", 5],
  73: ["Averses de pluie et neige mêlées faibles", 5],
  74: ["Averses de pluie et neige mêlées", 5],
  75: ["Averses de pluie et neige mêlées fortes", 5],
  76: ["Averses de pluie et neige mêlées faibles et nombreuses", 5],
  77: ["Averses de pluie et neige mêlées fréquentes"],
  78: ["Averses de pluie et neige mêlées fortes et fréquentes", 5],
  100: ["Orages faibles et locaux", 7],
  101: ["Orages locaux", 7],
  102: ["Orages fort et locaux", 7],
  103: ["Orages faibles", 7],
  104: ["Orages", 7],
  105: ["Orages forts", 7],
  106: ["Orages faibles et fréquents", 7],
  107: ["Orages fréquents", 7],
  108: ["Orages forts et fréquents", 7],
  120: ["Orages faibles et locaux de neige ou grésil", 7],
  121: ["Orages locaux de neige ou grésil", 7],
  122: ["Orages locaux de neige ou grésil", 7],
  123: ["Orages faibles de neige ou grésil", 7],
  124: ["Orages de neige ou grésil", 7],
  125: ["Orages de neige ou grésil", 7],
  126: ["Orages faibles et fréquents de neige ou grésil", 7],
  127: ["Orages fréquents de neige ou grésil", 7],
  128: ["Orages fréquents de neige ou grésil", 7],
  130: ["Orages faibles et locaux de pluie et neige mêlées ou grésil", 7],
  131: ["Orages locaux de pluie et neige mêlées ou grésil", 7],
  132: ["Orages fort et locaux de pluie et neige mêlées ou grésil", 7],
  133: ["Orages faibles de pluie et neige mêlées ou grésil", 7],
  134: ["Orages de pluie et neige mêlées ou grésil", 7],
  135: ["Orages forts de pluie et neige mêlées ou grésil", 7],
  136: ["Orages faibles et fréquents de pluie et neige mêlées ou grésil", 7],
  137: ["Orages fréquents de pluie et neige mêlées ou grésil", 7],
  138: ["Orages forts et fréquents de pluie et neige mêlées ou grésil", 7],
  140: ["Pluies orageuses", 7],
  141: ["Pluie et neige mêlées à caractère orageux", 7],
  142: ["Neige à caractère orageux", 7],
  210: ["Pluie faible intermittente", 3],
  211: ["Pluie modérée intermittente", 3],
  212: ["Pluie forte intermittente", 3],
  220: ["Neige faible intermittente", 3],
  221: ["Neige modérée intermittente", 3],
  222: ["Neige forte intermittente", 3],
  230: ["Pluie et neige mêlées", 5],
  231: ["Pluie et neige mêlées", 5],
  232: ["Pluie et neige mêlées", 5],
  235: ["Averses de grêle", 4],
};

let imgArray = [
  "img/brouillard.png",
  "img/eclaircie.png",
  "img/ensoleille.png",
  "img/giboulee.png",
  "img/grele.png",
  "img/neige.png",
  "img/nuageux.png",
  "img/orageux.png",
  "img/pluie_moderee.png",
  "img/pluie.png",
  "img/tres_nuageux.png",
];
